---
swagger: "2.0"
info:
  title: Red Hat Event API
  description: Red Hat Event API v1.0 - An API that gives information about the Red
    Hat Event
  version: 1.1.0
paths:
  /location:
    get:
      summary: Get Location
      description: Get the location of the next RedHat Event
      operationId: GetLocation
      responses:
        200:
          description: OK
  /timeframe:
    get:
      summary: Get Timeframe
      description: Get the timeframe of the next RedHat Event
      operationId: GetTimeframe
      responses:
        200:
          description: OK
  /participants:
    get:
      summary: Get all participants
      description: Get all the participants
      operationId: GetParticipants
      responses:
        200:
          description: OK
securityDefinitions:
  apikey:
    type: apiKey
    description: Use a 3scale API Key
    name: api-key
    in: header
security:
- apikey: []
