---
swagger: '2.0'
info:
  title: RHTE API v1.0
  description: An API that gives information about the Red Hat Tech Exchange.
  version: 1.0.0
paths:
  /location:
    get:
      summary: Get Next RHTE Location
      description: Get the location of the next RedHat Tech Exchange
      operationId: GetLocation
      responses:
        200:
          description: OK
  /timeframe:
    get:
      summary: Get Next RHTE Timeframe
      description: Get the timeframe of the next RedHat Tech Exchange
      operationId: GetTimeframe
      responses:
        200:
          description: OK
securityDefinitions:
  apikey:
    type: apiKey
    description: Use a 3scale API Key
    name: api-key
    in: header
security:
- apikey: []
